version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: photo-change-backend
    ports:
      - "8080:8080"
    volumes:
      - photo_uploads:/app/uploads
      - photo_templates:/app/templates
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: photo-change-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  photo_uploads:
    driver: local
  photo_templates:
    driver: local